version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - amimart
      - bdeneux
      - ccamel
    assignees:
      - amimart
      - bdeneux
      - ccamel
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - amimart
      - bdeneux
      - ccamel
    assignees:
      - amimart
      - bdeneux
      - ccamel
