version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - amimart
      - bdeneux
      - ccamel
    assignees:
      - amimart
      - bdeneux      
      - ccamel
