name: Build

on:
  workflow_call:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-wasm:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Install cargo make
        uses: davidB/rust-cargo-make@v1

      - name: Build wasm
        run: cargo make wasm

      - name: Prepare size limit
        run: |
          cat << EOF > package.json
          {
            "name": "contracts",
            "version": "1.0.0",
            "scripts": {
              "build": "cargo make wasm"
            },
            "devDependencies": {
              "@size-limit/preset-app": "^7.0.8"
            },
            "size-limit": [
              {
                "path": "target/wasm32-unknown-unknown/release/cw_template.wasm",
                "running": false,
                "brotli": false,
                "gzip": false
              }
            ]
          }
          EOF

      - name: Report wasm size limit
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
